name: parameters_on_demand

on:
  workflow_dispatch:
    inputs:
      dataFactoryName:
        description: 'Azure Data Factory'
        required: true
        default: 'ondemandadf'
      storageAccountName:
        description: 'Storage Name'
        required: true
        default: 'ondemamdstorage'
      storageSKU:
        description: 'Storage SKU'
        required: true
        default: 'Standard_LRS'
      deployStorage:
        description: 'bool parameter for storage deployment'
        required: true
        default: 'true'
      deployADF:
        description: 'bool parameter for ADF deployment'
        required: true
        default: 'true'
      deployEventHub:
        description: 'bool parameter for Event Hub deployment'
        required: true
        default: 'true'
      projectName:
        description: 'Storage Name'
        required: true
        default: 'bicepstaccountexr'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep files
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        dataFactoryName: '${{ github.event.inputs.dataFactoryName }}'
        storageAccountName: '${{ github.event.inputs.storageAccountName }}'
        storageSKU: '${{ github.event.inputs.storageSKU }}'
        projectName: '${{ github.event.inputs.projectName }}'
        deployADF: '${{ github.event.inputs.deployADF }}'
        deployEventHub: '${{ github.event.inputs.deployEventHub }}'
        deployStorage: '${{ github.event.inputs.deployStorage }}'
        template: ./main.bicep
        failOnStdErr: false
        
        
    
